# Color palette
BG_MAIN = "#eeebe2"
NEUTRAL = "#8e8985"
TEAL_MED = "#395b5c"
TEAL_VAR = "#385a5b"
TEAL_DARK = "#1c5a59"
BLUE_INST = "#104064"
BLUE_PRIMARY = "#003e63"
BLUE_DARKEST = "#19374f"

# Semantic colors
BTN_PRIMARY_BG = BLUE_PRIMARY
BTN_PRIMARY_FG = "#ffffff"
BTN_SECONDARY_BG = TEAL_MED
BTN_SECONDARY_FG = "#ffffff"
BTN_CANCEL_BG = "#cc0000"
BTN_CANCEL_FG = "#ffffff"
BTN_HOVER = TEAL_DARK

HEADER_BG = BLUE_PRIMARY
HEADER_FG = "#ffffff"

INPUT_BG = "#ffffff"
INPUT_BORDER = NEUTRAL

CHECKBOX_ACCENT = TEAL_DARK

SECTION_TITLE_COLOR = BLUE_DARKEST
BODY_TEXT_COLOR = BLUE_PRIMARY

PROGRESS_FG = TEAL_DARK
PROGRESS_BG = NEUTRAL

ERROR_COLOR = "#cc0000"
WARNING_COLOR = "#b87c00"
SUCCESS_COLOR = TEAL_DARK  # #1c5a59

# Tab bar colors
TAB_ACTIVE_BG = BLUE_PRIMARY  # #003e63
TAB_ACTIVE_FG = "#ffffff"
TAB_INACTIVE_BG = NEUTRAL  # #8e8985
TAB_INACTIVE_FG = "#ffffff"
TAB_HOVER_BG = TEAL_DARK  # #1c5a59

# Consolidation tab specific
BTN_REMOVE_BG = NEUTRAL  # #8e8985

# Font families (with fallback)
FONT_FAMILY = "Segoe UI"
FONT_TITLE = (FONT_FAMILY, 14, "bold")
FONT_SUBTITLE = (FONT_FAMILY, 11)
FONT_BODY = (FONT_FAMILY, 10)
FONT_SMALL = (FONT_FAMILY, 9)
FONT_HEADER_TITLE = (FONT_FAMILY, 18, "bold")
FONT_HEADER_SUBTITLE = (FONT_FAMILY, 11)

# Window dimensions
WINDOW_WIDTH = 720
WINDOW_HEIGHT = 700
WINDOW_MIN_WIDTH = 700
WINDOW_MIN_HEIGHT = 650
